Authentication
RAK-MANIAK/logical-creativity pull request #23
Opened 2023-10-03 18:43 UTC by AndriiBabushko

Next Auth **authentication** to **login** and **register** with credentials and **google provider** to authenticate with google credentials without registration.

2023-10-05 07:35 UTC, RAK-MANIAK requested changes

2023-10-05 07:35 UTC, FullmetalBober commented on .gitignore
Я думаю краще додати шлях
```/prisma/migrations```
замість 
```
/prisma/migrations/20230928051651_init/migration.sql
/prisma/migrations/20230930130912_/migration.sql
```

2023-10-05 07:35 UTC, FullmetalBober commented on next-env.d.ts
Хз нащо цей файл

2023-10-05 07:35 UTC, FullmetalBober commented on prisma/migrations/20230926114659_init/migration.sql
Удалити б цей файл

2023-10-05 07:35 UTC, FullmetalBober commented on prisma/migrations/20230927064214_init/migration.sql
Удалити б цей файл

2023-10-05 07:35 UTC, FullmetalBober commented on prisma/migrations/20230927071433_init/migration.sql
Удалити б цей файл

2023-10-05 07:35 UTC, FullmetalBober commented on prisma/schema.prisma
User думаю має бути обов'язковим
```
  User      User?      @relation(fields: [userId], references: [id])
  userId    Int?
  ```

2023-10-05 07:35 UTC, FullmetalBober commented on src/app/api/auth/[...nextauth]/authOptions.ts
findUnique тут краще підійде
```
        const user = await prisma.user.findFirst({
          where: {
            email: email,
          },
        });
```

2023-10-05 07:35 UTC, FullmetalBober commented on src/components/auth/Authorization.tsx
10000% це треба винести у окремий компонент, оскільки він прям повторюється з Registration.tsx
```
  if (authorized)
    return (
      <MyModal
        isTriggered={true}
        ModalHeaderElement={ModalHeaderElement}
        ModalBodyElement={ModalBodyElement}
        actionButton={{ text: 'Go back', color: 'warning', handler: () => router.back() }}
        size={'lg'}
        color={'warning'}
      />
    );
```

2023-10-05 07:35 UTC, RAK-MANIAK commented on src/components/auth/buttons/LoginButton.tsx
Я хз чия це пробулема next чи nextui, але вкладений as не підтримується, з'являються помилки, краще обгорни Button у SPALink
```
        <Button as={SPALink} href={'/auth/logout'} onClick={handleSignOut}>
          Sign Out
        </Button>
```

2023-10-05 07:35 UTC, RAK-MANIAK commented on src/components/auth/form/LoginForm.tsx
Шось текст бушує)
```Don&apos;t have an account?&nbsp;```

2023-10-05 07:35 UTC, RAK-MANIAK commented on src/components/auth/form/LoginForm.tsx
Юзаючи zod так вводити параметри вже непотрібно
```
          {...register('email', {
            required: true,
          })}
```

2023-10-05 07:35 UTC, RAK-MANIAK commented on src/components/layout/Header.tsx
Вроді це тут не треба
```'use client';```

2023-10-05 07:35 UTC, RAK-MANIAK commented on src/components/test/AnswersInputs.tsx
Еее а нашо 'use client';

2023-10-05 07:35 UTC, RAK-MANIAK commented on src/components/test/QuestionsInputs.tsx
Еее а нашо 'use client';

2023-10-05 07:35 UTC, RAK-MANIAK commented on src/components/ui/SPALink.tsx
Еее а нашо 'use client';

2023-10-05 07:35 UTC, RAK-MANIAK commented on src/lib/db.ts
а нащо ти тут робив зміни?

2023-10-09 17:20 UTC, AndriiBabushko commented
Merge this repo after teacher review the code I wrote

2023-10-09 17:33 UTC, RAK-MANIAK commented
> Merge this branch after teacher review the code I wrote

https://github.com/RAK-MANIAK/logical-creativity/pull/25

![image](https://github.com/RAK-MANIAK/logical-creativity/assets/106311891/2295c466-88de-4803-b927-fada9792f303)

2023-10-18 19:30 UTC, RAK-MANIAK approved these changes

2023-10-18 19:30 UTC, merged